language: node_js
node_js:
  - 5.6.0
script:
  - npm run eslint
notifications:
  slack:
    secure: OcdnBjbGtR6eu5UnMNS3w77nTw6X5wQ5Xn4yaR/7n7MKGV2luV8aa658XRSP5a4/EJ9jADMtoCIXHWGft5gXY4NzpR3jMFC/8QhcjRxHur0s7paY7D3mX1XqbSXwgTXWRM2OnmgQ4ZwZScflkYCKKR365tVtd9NcZ7mgF6yPV89/Ixhlp6xonMwzybbGCg7vYdQK6zX3Hg68QRfGz9wxgMjT6E0QWeOXwTY/42qFs7WaGocucXDjV1EmassVp3da1urDgBs2hL2tghcjqJFDMb8GTiYnK08GVCRWlvOpuwRrruuZdxbJgDaMeywDjC3H2zNcMQnwmfdvpYCBQFN8uxQDaEvnApd6Nfc1KoTS01sX3XSIj1Wr9fjOCk4dXqqx1sbXv2UwcAUJvjvsOpiKdj5zNisg3EDGlEOkP2um51n2O099w4AQRtEmOOQdJJVVMagwB4YPr1LoDIEg1kKzeC1qgg8y/utdw4J+Z7vXQNLFoA/WOnIfadCVHCMd2Fhk6tZKX6g6eN7soqtfFqsccdxHCMAIdcRs08+G1G4dVryTC4Gr8Xuo6hsF6a+KZdtC3HfrbSm7PXCiabP050VMGa0alenKwD5t6Li5smS0SwK+J2RUaWnMKkouPRr8uXIgIAMZFhDHmbXXWfTQOb/Z6fSPSEOE4bAAExtvCjNyfbA=
